### ISSUE TITLE
Serializer Interface

### ISSUE THREAD

**Issue by arnaspet** [subjective-php/psr-cache-redis#1]
Hey, nice, slim library by the way, will try to use it.
First complain: SerializerInterface should take `$context` as a second `serialize/unserialize` parameter.
Otherwise this Interface can have some issues in the future.

Example case i've encoutered:
Made JsonSerializer, `json_encode`, `json_decode` method takes additional parameters, which would be impossible to pass.

**Comment by chadicus** [comment]
This is a great suggestion. I'm moving the serializer into my [helper library](https://github.com/chadicus/psr-cache-helper/pull/2/files#diff-349932bcf3760797236c7e31d322bd29) I will definitely consider this change.

**Comment by chadicus** [comment]
Optionally you could construct your `JsonSerializer` with any options you wanted to use with encoding/decoding.
